//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string adminnumber { get; set; }
        public string adminname { get; set; }
        public string area { get; set; }
        public int build { get; set; }
        public byte[] picture { get; set; }
    }
}
