//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormManage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DormManageDataEntities : DbContext
    {
        public DormManageDataEntities()
            : base("name=DormManageDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<change> change { get; set; }
        public virtual DbSet<complain_admin> complain_admin { get; set; }
        public virtual DbSet<complain_dorm> complain_dorm { get; set; }
        public virtual DbSet<dorm> dorm { get; set; }
        public virtual DbSet<electricity> electricity { get; set; }
        public virtual DbSet<login_admin> login_admin { get; set; }
        public virtual DbSet<login_student> login_student { get; set; }
        public virtual DbSet<notice> notice { get; set; }
        public virtual DbSet<repair> repair { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<water> water { get; set; }
    }
}
